### ISSUE TITLE
Multiple MPU6050

### ISSUE THREAD

**Issue by martin072** [romybompart/py_imu_mpu6050#1]
Hi, 

I am trying to use 2 MPU6050 with your library, however, it does not seem to work?
Following is setup in main()

```
i2c = busio.I2C(SCL,SDA)
IMU1 = MPU6050(i2c,0x68)
IMU2 = MPU6050(i2c,0x69)
print ("Identification MPU6050-1 0x{:X} ".format(IMU1.whoami))
print ("Identification MPU6050-2 0x{:X} ".format(IMU2.whoami))
```

But the output gives:
```
Identification MPU6050-1 0x68
Identification MPU6050-2 0x68
```

The i2cdetect shows them correctly:

```
     0  1  2  3  4  5  6  7  8  9  a  b  c  d  e  f
00:          -- -- -- -- -- -- -- -- -- -- -- -- --
10: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
20: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
30: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
40: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
50: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
60: -- -- -- -- -- -- -- -- 68 69 -- -- -- -- -- --
70: -- -- -- -- -- -- -- --

```
Are multiple units supported?

**Comment by martin072** [comment]
Hmm, I do get the independent data from both Sensors, looks like the WHOAMI function does not work correctly..

**Comment by romybompart** [comment]
Hi Dear martin, I can't see why you have that issue.
Since the WHOAMI property only reads from the register 0x75 of your MPU device.
The reading is performed using the object created from the class MPU6050, that object is already identified with the address that you gave during the object creation. 

Can you do the following testing?, create only one object. 
IMU2 = MPU6050(i2c,0x69)
Then, ask for WhoIam
print ("Identification MPU6050-2 0x{:X} ".format(IMU2.whoami))

Let's see what you got!. I am sorry I didn't answer you back before. 

Best Regards

**Comment by martin072** [comment]
Hi, thanks for the reply. I decided not to use this setup anymore, so can't really test it anymore sorry.
